//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDocEditor {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDocEditor.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   定数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Const {
            get {
                return ResourceManager.GetString("Const", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IoType_In {
            get {
                return ResourceManager.GetString("IoType_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InOut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IoType_InOut {
            get {
                return ResourceManager.GetString("IoType_InOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IoType_Out {
            get {
                return ResourceManager.GetString("IoType_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライブラリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列挙体 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TypeEnum {
            get {
                return ResourceManager.GetString("TypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   構造体 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TypeStruct {
            get {
                return ResourceManager.GetString("TypeStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   別名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TypeTypedef {
            get {
                return ResourceManager.GetString("TypeTypedef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共用体 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TypeUnion {
            get {
                return ResourceManager.GetString("TypeUnion", resourceCulture);
            }
        }
    }
}
